# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "stackfuture"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Microsoft"]

[dependencies]

[dev-dependencies]
futures = { version = "0.3", features = ["executor"] }
